### ISSUE TITLE
Strategy destructor should be virtual

### ISSUE THREAD

**Issue by jquinn47** [SaintDubious/DubiousEngine#1]
Hola! Been reading the blog. Liked all the C++ ones. I went down the "show me the code" rabbit hole almost immediately after browsing the table of contents for the physics section. 

Looks like the Collision Strategy base class needs to add virtual to its destructor to avoid slicing.

https://github.com/SaintDubious/DubiousEngine/blob/5576f35a4ac226356952a6fff71d6613881f4862/Physics/src/Collision_strategy.h#L27

**Comment by SaintDubious** [comment]
Thanks for that. I've committed the change
